name: Run Tests

# 1. Se dispara automáticamente con cada push a main
on:
  push:
    branches:
      - master

jobs:
  # 7. Job llamado tests
  tests:
    # 8. Se ejecuta en la última versión de Python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]  # Puedes cambiar a la versión de Python que necesites

    steps:
      # 9.1. Descargar el código
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      # 9.2. Configurar Python y instalar dependencias
      - name: Configurar Python e instalar dependencias
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 9.3. Ejecutar pytest
      - name: Ejecutar tests con pytest
        run: pytest
